[package]
name = "bls-gadgets"
version = "0.1.0"
authors = ["Georgios Konstantopoulos <me@gakonst.com>", "Kobi Gurkan <kobigurk@gmail.com>"]
edition = "2018"

[dependencies]
bls-crypto = { path = "../bls-crypto" }

algebra = { git = "https://github.com/celo-org/zexe", features = ["derive", "bls12_377", "sw6", "edwards_sw6", "parallel"], rev = "3ec3bcca4a9b2bb25022b1dac7997b639c8fa3ff" }
r1cs-core = { git = "https://github.com/celo-org/zexe", default-features = false, rev = "3ec3bcca4a9b2bb25022b1dac7997b639c8fa3ff"  }
r1cs-std = { git = "https://github.com/celo-org/zexe", default-features = false, features = ["bls12_377", "edwards_sw6", "parallel"], rev = "3ec3bcca4a9b2bb25022b1dac7997b639c8fa3ff"  }
crypto-primitives = { git = "https://github.com/celo-org/zexe", default-features = false, features = ["parallel"], rev = "3ec3bcca4a9b2bb25022b1dac7997b639c8fa3ff"  }

# used only when exporting our test helpers to be used in the snark crate
rand_xorshift = { version = "0.2", optional = true }
rand = { version = "0.7" , optional = true }
tracing = "0.1.13"

[dev-dependencies]
rand_xorshift = { version = "0.2" }
rand = { version = "0.7" }
groth16 = { git = "https://github.com/celo-org/zexe" }
bls-crypto = { path = "../bls-crypto", features = ["test-helpers"] }

[features]
test-helpers = ["rand", "rand_xorshift"]
