[workspace]

members = [ 
    "crates/bls-crypto", 
    "crates/bls-gadgets",
    "crates/epoch-snark",
]

[profile.release]
opt-level = 3
lto = "thin"
incremental = true

# build all our deps in release mode 
[profile.dev.package."*"]
opt-level = 3

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = "thin"
incremental = true
debug-assertions = false


[profile.test]
opt-level = 3
incremental = true
debug-assertions = true
debug = true

[patch."https://github.com/scipr-lab/zexe"]
algebra = { version = "0.1.0", package = "algebra", git = "https://github.com/celo-org/zexe", branch = "kobigurk/fix_from_random_bytes" }
ff-fft = { package = "ff-fft", git = "https://github.com/celo-org/zexe", branch = "kobigurk/fix_from_random_bytes" }
groth16 = { package = "groth16", git = "https://github.com/celo-org/zexe", branch = "kobigurk/fix_from_random_bytes" }
r1cs-core = { package = "r1cs-core", git = "https://github.com/celo-org/zexe", branch = "kobigurk/fix_from_random_bytes" } 
r1cs-std = { package = "r1cs-std", git = "https://github.com/celo-org/zexe", branch = "kobigurk/fix_from_random_bytes" } 
gm17 = { package = "gm17", git = "https://github.com/celo-org/zexe", branch = "kobigurk/fix_from_random_bytes" } 
crypto-primitives = { package = "crypto-primitives", git = "https://github.com/celo-org/zexe", branch = "kobigurk/fix_from_random_bytes" }  
bench-utils = { package = "bench-utils", git = "https://github.com/celo-org/zexe", branch = "kobigurk/fix_from_random_bytes" }  
