version: 2

defaults: &defaults
  working_directory: ~/app

rust_defaults: &rust_defaults
  <<: *defaults
  docker:
    - image: circleci/rust:latest

go_defaults: &go_defaults
  <<: *defaults
  docker:
    - image: circleci/go:latest

jobs:
  checkout-repo:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - persist_to_workspace:
          root: .
          paths: .

  go-module-tests:
    <<: *go_defaults
    working_directory: ~/pp
    docker:
      - image: circleci/go:latest
    steps:
      - attach_workspace:
          at: ~/app
      - run: cd go/cmd/example && go run main.go

  ultralight-tests:
    <<: *rust_defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: rustup install nightly
      - run: cd ultralight && cargo +nightly test --release

  zexe-tests:
    <<: *rust_defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: rustup install nightly
      - run: cd zexe && cargo +nightly test --release

workflows:
  version: 2
  run-tests:
    jobs:
      - checkout-repo
      - ultralight-tests:
          requires:
            - checkout-repo
      - zexe-tests:
          requires:
            - checkout-repo
