version: 2
jobs:
  ultralight-tests:
    docker:
      - image: circleci/rust:latest

    steps:
      - checkout
      - run: cd ultralight && cargo +nightly test

  zexe-tests:
    docker:
      - image: circleci/rust:latest

    steps:
      - checkout
      - run: cargo test

workflows:
  version: 2
  build-and-test:
    jobs:
      - ultralight-tests
      - zexe-tests
