version: 2

defaults: &defaults
  working_directory: ~/app

rust_defaults: &rust_defaults
  <<: *defaults
  docker:
    - image: circleci/rust:latest
  resource_class: xlarge

jobs:
  checkout-repo:
    <<: *rust_defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - persist_to_workspace:
          root: .
          paths: .

  bls-tests:
    <<: *rust_defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Install clippy and cargo-audit
          command: |
            cargo install cargo-audit
            rustup component add clippy
      - restore_cache:
          keys:
            - v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build
          command: cargo build --release --all-features
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/release
          key: v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Run tests
          command: cargo test --release
          no_output_timeout: 30m
      - run:
          name: Run non-compat tests in bls-crypto
          command: cd crates/bls-crypto && cargo test --release --no-default-features
          no_output_timeout: 30m
      - run:
          name: Run non-compat tests in bls-gadgets
          command: cd crates/bls-gadgets && cargo test --release --no-default-features
          no_output_timeout: 30m
      - run:
          name: Run non-compat tests in epoch-snark
          command: cd crates/epoch-snark && cargo test --release --no-default-features
          no_output_timeout: 30m
      - run:
          name: Check Style
          command: |
            cargo fmt --all -- --check
            cargo clippy --release --all-targets --all-features -- -D warnings
      - run:
          name: Audit Dependencies
          command: cargo audit
      - persist_to_workspace:
          root: .
          paths: target/release

workflows:
  version: 2
  run-tests:
    jobs:
      - checkout-repo
      - bls-tests:
          requires:
            - checkout-repo
