version: 2
jobs:
  instal-dependencies:
    docker:
      - image: circleci/rust:latest
    steps:
      - run: rustup install nightly

  ultralight-tests:
    docker:
      - image: circleci/rust:latest

    steps:
      - checkout
      - run: cd ultralight && cargo +nightly test --release

  zexe-tests:
    docker:
      - image: circleci/rust:latest

    steps:
      - checkout
      - run: cd zexe && cargo test

workflows:
  version: 2
  run-tests:
    jobs:
      - install-dependencies
      - ultralight-tests:
          requires:
            - install-dependencies
      - zexe-tests:
          requires:
            - install-dependencies
