version: 2

defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/rust:latest

jobs:
  install-dependencies:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - run: rustup install nightly
      - persist_to_workspace:
          root: .
          paths: .


  ultralight-tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: ls
      - run: cd ultralight && cargo +nightly test --release

  zexe-tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: cd zexe && cargo test

workflows:
  version: 2
  run-tests:
    jobs:
      - install-dependencies
      - ultralight-tests:
          requires:
            - install-dependencies
      - zexe-tests:
          requires:
            - install-dependencies
