version: 2

defaults: &defaults
  working_directory: ~/app

rust_defaults: &rust_defaults
  <<: *defaults
  docker:
    - image: circleci/rust:latest

go_defaults: &go_defaults
  <<: *defaults
  docker:
    - image: circleci/go:latest

jobs:
  checkout-repo:
    <<: *rust_defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - persist_to_workspace:
          root: .
          paths: .

  bls-tests:
    <<: *rust_defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: rustup install 1.36.0
      - run: cargo build --release && cargo test --release
      - persist_to_workspace:
          root: .
          paths: target/release

  go-module-tests:
    <<: *go_defaults
    working_directory: ~/app
    docker:
      - image: circleci/golang:latest
    steps:
      - attach_workspace:
          at: ~/app
      - run: cd ~/app/go/cmd/example && go run main.go
      - run: cd ~/app/go && go test

workflows:
  version: 2
  run-tests:
    jobs:
      - checkout-repo
      - bls-tests:
          requires:
            - checkout-repo
      - go-module-tests:
          requires:
            - checkout-repo
            - bls-tests