[package]
name = "bls_snark"
version = "0.1.0"
authors = ["Kobi Gurkan <kobigurk@gmail.com>", "Michael Straka <mstraka@celo.org>"]
edition = "2018"

[dependencies]
snark-gadgets = { path = "../../zexe/snark-gadgets" }
snark = { path = "../../zexe/snark" }
algebra = { path = "../../zexe/algebra" }
rand = { version = "0.4" }

[lib]
crate-type = ["lib", "staticlib"]