[package]
name = "bls-snark-sys"
version = "0.1.4"
authors = ["Georgios Konstantopoulos <me@gakonst.com>"]
edition = "2018"

[dependencies]
bls-crypto = { path = "../bls-crypto", features = ["compat"] }
epoch-snark = { path = "../epoch-snark", features = ["compat"] }

algebra = { git = "https://github.com/scipr-lab/zexe", default-features = false, features = ["bls12_377", "parallel"], rev = "38b6f6f2c6b9a6a1b5e8eb90b1287c98b06520d1" }
once_cell = "1.4.0"
rand = "0.7.3"
log = "0.4.8"

[lib]
crate-type = ["lib", "staticlib"]

[dev-dependencies]
groth16 = { git = "https://github.com/scipr-lab/zexe", features = ["parallel"], rev = "38b6f6f2c6b9a6a1b5e8eb90b1287c98b06520d1" }
r1cs-core = { git = "https://github.com/scipr-lab/zexe", rev = "38b6f6f2c6b9a6a1b5e8eb90b1287c98b06520d1" }
hex = "0.4.2"

